#!/bin/sh
# sends a dummy telex message every 15 seconds

#usage sendmessage mqtt-host mqtt-port

mqttserver=localhost
mqttport=1883
interval=15

if [ $# -gt 0 ]; then
    mqttserver="$1"
fi

if [ $# -gt 1 ]; then
    mqttport="$2"
fi

if [ $# -gt 2 ]; then
    interval="$3"
fi

echo "sending messages to to $mqttserver:$mqttport"

while true; do
#    echo +++ yet another interesting message 1 +++
#    echo +++ yet another interesting message 2 +++
#    echo +++ yet another interesting message 3 +++
#    echo +++ yet another interesting message 4 +++
    echo +++ chirp, chirp, chirp
    echo +++ hello from space, TTN!
    echo +++ TTNSAT calling here
    echo +++ thanks to ESA, Space Norway, Norwegian Space Centre, and Semtech
    echo +++ let\'s build this thing together
    echo +++ the secret code is 384206
    echo +++ goodbye!
    sleep $interval
done | mosquitto_pub -l -t "telex/incoming-sat/" -h $mqttserver -p $mqttport
